name: CI Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Go version
        run: |
          # go x.y.z という行にバージョンが書いてある想定
          GO_VERSION=$(awk '/^go / {print $2}' go.mod)
          echo "GO_VERSION=$GO_VERSION" >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout formatting
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "❌ Code formatting issues found! Run 'gofmt -w .' to fix them."
            exit 1
          else
            echo "✅ Code is properly formatted."
          fi

      - name: Install dependencies
        run: |
          go mod tidy
          go mod verify

      - name: Test
        run: go test -tags=test -cover -coverprofile=coverage.txt ./...

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage.txt

  code_coverage:
    name: "Code coverage report"
    if: github.event_name == 'pull_request' # Do not run when workflow is triggered by push to main branch
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      actions: read
      pull-requests: write
    steps:
      - uses: fgrosse/go-coverage-report@v1.2.0
